### ISSUE TITLE
Doesn't work for VSCode-inside installations or code.exe not in path

### ISSUE THREAD

**Issue by WilliamStone** [joaomrsouza/better-extension-manager#5]
Hello @joaomrsouza !
    IMO this extension is a saver for VSCode, however it cannot work for my installation. The extension works by composing and invoking command line, with exe file name defaults to `code`. However in my installation this is not the case. There are a few reasons that make the extension not working correctly:
1. I installed VSCode insider version, whose exe file name is `Code - Insiders.exe`, not `code`;
2. I installed VSCode without adding exe file to windows PATH environment variables, which is an option in installer, thus doing this is valid and reasonable;
3. Actually I installed VSCode release version and VSCode Insider version side by side, which means even if I add VSCode exe file to path during installation, It still may mix up, causing the extension to work on a different VSCode installation. 

So I suggest: **get full path of current running VSCode exe file** and use it to compose command line. If this is technically impossible, at least **add a setting item for exe file full path of current VSCode installation instance**, and use it to compose command line. So the command line can invoke correct VSCode installation instance.

**Comment by joaomrsouza** [comment]
Hello @WilliamStone thanks for the feedback!! I didn't know of this instalation option, and didn't though about many vscode installs in the same machine. I agree with the solution proposed, I don't think it's possible to determine the exe location automatically but I'll do some search about it, otherwise I will implement an option to specify the path manually using the `code` command as a fallback. Again, thanks for the feedback, glad to see that other people are liking it!!

**Comment by joaomrsouza** [comment]
Fixed! The extension also was updated on VSCode marketplace (v1.2.0), thanks again to report the problem, hope this solves it!
